backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - {
              label: 'Background Image',
              name: 'background_image',
              widget: image,
            }
          - { label: 'Title Image', name: 'image', widget: image }
          - {
              label: 'Upcoming Events Section Title',
              name: 'events_button_title',
              widget: 'string',
            }
          - { label: 'Heading', name: 'title', widget: 'string' }
          - {
              label: 'Heading Description',
              name: 'description',
              widget: 'text',
            }
          - {
              label: 'Artist Section Title',
              name: 'artist_spotlight',
              widget: 'string',
            }
          - { label: 'Artist Image', name: 'artist_image', widget: image }
          - { label: 'Artist Name', name: 'artist_name', widget: 'string' }
          - {
              label: 'Artist Description',
              name: 'artist_description',
              widget: 'string',
            }
          - { label: 'Tickets Link', name: 'tickets_url', widget: 'string' }
          - {
              label: 'Artist Website',
              name: 'artist_website',
              widget: 'string',
            }
          - { label: 'Playlist', name: 'spotify_playlist', widget: 'string' }
          - {
              label: 'Food Section Title',
              name: 'food_and_drinks_title',
              widget: 'string',
            }
          - {
              label: 'Food Section Description',
              name: 'food_and_drinks_description',
              widget: 'text',
            }
      - file: 'src/pages/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - {
              label: 'Background Image',
              name: 'background_image',
              widget: image,
            }
          - { label: 'Page Title', name: 'about_title', widget: 'string' }
          - { label: 'Heading', name: 'title', widget: 'string' }
          - {
              label: 'Heading Description',
              name: 'description',
              widget: 'text',
            }
          - {
              label: 'Community Section Title',
              name: 'community_title',
              widget: 'string',
            }
          - {
              label: 'Community Paragraph 1',
              name: 'community_description_p1',
              widget: 'text',
            }
          - {
              label: 'Community Paragraph 2',
              name: 'community_description_p2',
              widget: 'text',
            }
          - {
              label: 'Community Paragraph 3',
              name: 'community_description_p3',
              widget: 'text',
            }
          - {
              label: 'Culture Section Title',
              name: 'culture_title',
              widget: 'string',
            }
          - {
              label: 'Culture Paragraph 1',
              name: 'culture_description_p1',
              widget: 'text',
            }
          - {
              label: 'Culture Paragraph 2',
              name: 'culture_description_p2',
              widget: 'text',
            }
          - {
              label: 'Craft Section Title',
              name: 'craft_title',
              widget: 'string',
            }
          - {
              label: 'Craft Paragraph 1',
              name: 'craft_description_p1',
              widget: 'text',
            }
          - {
              label: 'Craft Paragraph 2',
              name: 'craft_description_p2',
              widget: 'text',
            }
          - {
              label: 'Craft Paragraph 3',
              name: 'craft_description_p3',
              widget: 'text',
            }
      - file: 'src/pages/calendar.md'
        label: 'Calendar Page'
        name: 'calendar'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'calendar-page',
            }
          - {
              label: 'Background Image',
              name: 'background_image',
              widget: image,
            }
          - { label: 'Page Title', name: 'title', widget: 'string' }
      - file: 'src/pages/community.md'
        label: 'Community Page'
        name: 'community'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'community-page',
            }
          - {
              label: 'Background Image',
              name: 'background_image',
              widget: image,
            }
          - { label: 'Page Title', name: 'title', widget: 'string' }
      - file: 'src/pages/foodpage.md'
        label: 'Food & Drink Page'
        name: 'foodpage'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'foodpage',
            }
          - label: 'Manual PDF'
            name: 'menu'
            widget: 'file'
            default: 'src/assets/pdf/menu.pdf'
